import logging
from celery import shared_task

logger = logging.getLogger(__name__)

class PromotionPolicy:
    """
    Evaluates whether an artifact (Blueprint or Tool) meets the 
    criteria for promotion to production.
    """
    
    @classmethod
    def can_promote_blueprint(cls, blueprint_id: int) -> tuple[bool, str]:
        from benchmarking.models import BenchmarkRun
        
        runs = BenchmarkRun.objects.filter(experiment__blueprint_id=blueprint_id)
        if not runs.exists():
            return False, "Blueprint has never been benchmarked."
            
        recent_runs = runs.order_by('-timestamp')[:3]
        
        # Simple policy: average semantic score across last 3 runs must be > 0.8
        scores = [r.average_semantic_score for r in recent_runs if r.average_semantic_score]
        if not scores:
            return False, "Benchmark runs completed but no semantic scores available."
            
        avg_score = sum(scores) / len(scores)
        if avg_score >= 0.8:
            return True, f"Passed. Average semantic score {avg_score:.2f} >= 0.8"
        else:
            return False, f"Failed. Average semantic score {avg_score:.2f} < 0.8"
            
    @classmethod
    def can_promote_tool(cls, tool_id: int) -> tuple[bool, str]:
        # Tool promotion logic (could involve a dry-run test suite)
        # For now, requires manual review
        return False, "Tool promotion requires manual admin review."


@shared_task
def night_manager_task():
    """
    Celery Beat task that runs during low-usage hours.
    Discovers unpromoted blueprints and runs them against standard benchmarks
    so users have data to decide on promotion.
    """
    logger.info("Night Manager starting...")
    from .models import CognitiveBlueprint
    from benchmarking.models import Experiment, ScenarioGroup
    from benchmarking.runner import run_benchmark_suite

    # Find the standard scenario group for benchmarking
    standard_group = ScenarioGroup.objects.filter(name='Standard Core').first()
    if not standard_group:
        logger.warning("Night Manager: No 'Standard Core' ScenarioGroup found. Skipping benchmarking.")
        return

    # Check all blueprints for recent benchmark runs
    blueprints = CognitiveBlueprint.objects.all()

    experiment_count = 0
    for bp in blueprints:
        # Create an experiment if one doesn't exist for this blueprint
        experiment, created = Experiment.objects.get_or_create(
            name=f"Night Manager: {bp.name}",
            defaults={
                'description': f"Auto-generated by NightManager for blueprint: {bp.name}",
                'scenario_group': standard_group,
                'configuration': {
                    'generation_target': 'blueprint',
                    'blueprint_id': bp.id,
                    'rag_strategy': 'Agentic',
                },
            }
        )

        if created:
            logger.info(f"Night Manager created new experiment for {bp.name}")

            # Run the benchmark suite synchronously (we're in a Celery worker)
            try:
                if experiment.scenario_group and experiment.scenario_group.scenarios.exists():
                    corpus = experiment.corpus
                    if corpus:
                        run_benchmark_suite(experiment, corpus, log_callback=logger.info)
                        experiment_count += 1
                    else:
                        logger.info(f"Night Manager: Skipping {bp.name} — no corpus assigned.")
                else:
                    logger.info(f"Night Manager: Skipping {bp.name} — scenario group has no scenarios.")
            except Exception as e:
                logger.exception(f"Night Manager: Failed to benchmark {bp.name}: {e}")

    logger.info(f"Night Manager finished. Ran {experiment_count} experiments.")
