# Generated by Django 5.2.7 on 2026-04-23 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metacognition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. 'OpenAI GPT-4o'", max_length=255),
                ),
                ("provider", models.CharField(default="openai", max_length=50)),
                (
                    "api_url",
                    models.URLField(
                        default="https://api.openai.com/v1/chat/completions"
                    ),
                ),
                (
                    "api_model_name",
                    models.CharField(help_text="e.g. 'gpt-4o'", max_length=255),
                ),
                ("context_window", models.IntegerField(default=128000)),
            ],
        ),
        migrations.CreateModel(
            name="LocalAIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name (e.g. 'Qwen 2.5 3B')", max_length=255
                    ),
                ),
                (
                    "hf_model_id",
                    models.CharField(help_text="HuggingFace ID", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Notes on capabilities, VRAM usage, etc."
                    ),
                ),
                (
                    "load_in_4bit",
                    models.BooleanField(
                        default=True,
                        help_text="Use 4-bit quantization (Recommended for 6GB VRAM)",
                    ),
                ),
                (
                    "context_window",
                    models.IntegerField(default=4096, help_text="Max tokens"),
                ),
                (
                    "is_system_active",
                    models.BooleanField(
                        default=False,
                        help_text="Is this currently loaded in the inference server VRAM?",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, default="New Conversation", max_length=255
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cognitive blueprint driving this conversation, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="metacognition.cognitiveblueprint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="PromptResponseLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("system_prompt", models.TextField()),
                ("user_prompt", models.TextField(blank=True, null=True)),
                ("generated_response", models.TextField()),
                ("rag_selections", models.TextField(blank=True, null=True)),
                (
                    "user_feedback",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Thumb Up"), (-1, "Thumb Down")],
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="llm_api.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_external",
                    models.BooleanField(
                        default=False,
                        help_text="Route requests to external API instead of local GPU.",
                    ),
                ),
                (
                    "active_external",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="llm_api.externalaimodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Must match ExternalAIModel provider (e.g., 'openai')",
                        max_length=50,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Stored as plaintext. Consider django-fernet-fields for production.",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
