# Generated by Django 5.2.7 on 2025-11-24 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promptresponselog",
            options={"ordering": ["-created_at"]},
        ),
    ]
