# Generated by Django 5.2.7 on 2026-05-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localaimodel",
            name="is_system_active",
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_tokenizer_id",
                    models.CharField(
                        default="Qwen/Qwen2.5-3B-Instruct",
                        help_text="Loaded into CPU RAM to count tokens, even if local VRAM model is disabled.",
                        max_length=255,
                    ),
                ),
                (
                    "active_local_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="The PyTorch model loaded into VRAM. Leave blank to exclusively use Ollama/External APIs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="llm_api.localaimodel",
                    ),
                ),
            ],
        ),
    ]
