# Generated by Django 5.2.7 on 2026-03-12 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name (e.g. 'Phi-3 Mini')", max_length=255
                    ),
                ),
                (
                    "hf_model_id",
                    models.CharField(
                        help_text="HuggingFace ID (e.g. 'microsoft/Phi-3-mini-4k-instruct')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Notes on capabilities, VRAM usage, etc."
                    ),
                ),
                (
                    "load_in_4bit",
                    models.BooleanField(
                        default=True,
                        help_text="Use 4-bit quantization (Recommended for 6GB VRAM)",
                    ),
                ),
                (
                    "context_window",
                    models.IntegerField(default=4096, help_text="Max tokens"),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_intent",
                    models.CharField(
                        blank=True,
                        help_text="Why was this model activated? (e.g. 'Benchmarking Regex')",
                        max_length=255,
                    ),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
