# Generated by Django 6.0.5 on 2026-06-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0002_remove_localaimodel_is_system_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="active_ollama_model",
            field=models.CharField(
                blank=True,
                help_text="The selected model currently running in the local Ollama container.",
                max_length=255,
                null=True,
            ),
        ),
    ]
