# Generated by Django 6.0.5 on 2026-06-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0003_systemconfiguration_active_ollama_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponselog",
            name="git_commit_hash",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="promptresponselog",
            name="parent_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_logs",
                to="llm_api.promptresponselog",
            ),
        ),
    ]
