# Generated by Django 5.2.7 on 2026-03-24 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0003_alter_promptresponselog_user"),
        ("metacognition", "0002_moderationlist_responseschema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="blueprint",
            field=models.ForeignKey(
                blank=True,
                help_text="The cognitive blueprint driving this conversation, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="metacognition.cognitiveblueprint",
            ),
        ),
    ]
