# Generated by Django 6.0.6 on 2026-06-16 23:54

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0004_promptresponselog_git_commit_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="api_key",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
