# Generated by Django 6.0.6 on 2026-06-17 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0005_alter_userapikey_api_key"),
        ("metacognition", "0005_reasoningstep_sub_blueprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="blueprint",
        ),
        migrations.AddField(
            model_name="promptresponselog",
            name="blueprint",
            field=models.ForeignKey(
                blank=True,
                help_text="The cognitive blueprint driving this conversation, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="metacognition.cognitiveblueprint",
            ),
        ),
    ]
