# Generated by Django 6.0.6 on 2026-06-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0006_remove_conversation_blueprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponselog",
            name="input_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of tokens in the prompt"
            ),
        ),
        migrations.AddField(
            model_name="promptresponselog",
            name="output_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of tokens in the generated response"
            ),
        ),
    ]
