# Generated by Django 6.0.6 on 2026-06-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0007_promptresponselog_input_tokens_and_more"),
        ("metacognition", "0009_reasoningstep_parent_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponselog",
            name="reasoning_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_logs",
                to="metacognition.reasoningstep",
            ),
        ),
        migrations.AddField(
            model_name="promptresponselog",
            name="step_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUCCESS", "Success"),
                    ("RETRY", "Retry (Self)"),
                    ("FAILURE", "Failure (Re-plan)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
