# Generated by Django 6.0.6 on 2026-07-01 00:55

from django.db import migrations, models

def migrate_rag_text_to_json(apps, schema_editor):
    PromptResponseLog = apps.get_model("llm_api", "PromptResponseLog")
    for log in PromptResponseLog.objects.exclude(rag_selections__isnull=True).exclude(rag_selections=""):
        old_text = log.rag_selections
        if old_text:
            log.rag_selections_json = [{
                "model": "LegacyText",
                "preview": old_text[:200] + "..." if len(old_text) > 200 else old_text
            }]
            log.save(update_fields=['rag_selections_json'])


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0008_promptresponselog_reasoning_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponselog",
            name="rag_selections_json",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(migrate_rag_text_to_json, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="promptresponselog",
            name="rag_selections",
        ),
        migrations.RenameField(
            model_name="promptresponselog",
            old_name="rag_selections_json",
            new_name="rag_selections",
        ),
    ]
