# Generated by Django 6.0.6 on 2026-07-14 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0009_migrate_rag_selections_to_json"),
        ("metacognition", "0017_cognitiveblueprint_is_autonomous"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoRAAdapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Adapter short name (e.g., 'python_coder')",
                        max_length=255,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Absolute path to the adapter directory on disk or HF hub ID",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this adapter specializes in."
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="promptresponselog",
            index=models.Index(
                fields=["conversation"], name="llm_api_pro_convers_61029a_idx"
            ),
        ),
        migrations.AddField(
            model_name="loraadapter",
            name="base_model",
            field=models.ForeignKey(
                help_text="The base model this adapter was trained for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adapters",
                to="llm_api.localaimodel",
            ),
        ),
    ]
