# Generated by Django 6.0.7 on 2026-07-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0011_loraadapter_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="active_vllm_model",
            field=models.CharField(
                blank=True,
                help_text="Model name loaded in the vLLM service (e.g., Qwen/Qwen2.5-3B-Instruct).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="use_vllm",
            field=models.BooleanField(
                default=False,
                help_text="Enable the vLLM backend (requires the vLLM Docker container to be running).",
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="vllm_endpoint",
            field=models.URLField(
                default="http://vllm:8000/v1",
                help_text="Base URL for the vLLM OpenAI-compatible API.",
            ),
        ),
    ]
