# Generated by Django 6.0.7 on 2026-07-14 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0012_systemconfiguration_active_vllm_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemconfiguration",
            name="use_vllm",
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="hosting_backend",
            field=models.CharField(
                choices=[
                    ("pytorch", "Local PyTorch (CPU/GPU)"),
                    ("vllm", "vLLM Service"),
                    ("ollama", "Ollama Container"),
                ],
                default="pytorch",
                help_text="Select the primary inference engine used by the local proxy server.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="active_local_model",
            field=models.ForeignKey(
                blank=True,
                help_text="The PyTorch model loaded into VRAM. Used only when 'Local PyTorch' is the active hosting backend.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="llm_api.localaimodel",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="active_ollama_model",
            field=models.CharField(
                blank=True,
                help_text="The selected model running in the local Ollama container. Used only when 'Ollama Container' is the active hosting backend.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="active_vllm_model",
            field=models.CharField(
                blank=True,
                help_text="Model name loaded in the vLLM service (e.g., Qwen/Qwen2.5-3B-Instruct). Used only when 'vLLM Service' is the active hosting backend.",
                max_length=255,
                null=True,
            ),
        ),
    ]
