# Generated by Django 6.0.7 on 2026-07-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0013_remove_systemconfiguration_use_vllm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfiguration",
            name="active_ollama_model",
            field=models.ForeignKey(
                blank=True,
                help_text="The selected model running in the local Ollama container. Used only when 'Ollama Container' is the active hosting backend.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ollama_configurations",
                to="llm_api.localaimodel",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="active_vllm_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Model loaded in the vLLM service. Used only when 'Local vLLM Container' is the active hosting backend.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vllm_configurations",
                to="llm_api.localaimodel",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="hosting_backend",
            field=models.CharField(
                choices=[
                    ("pytorch", "Local PyTorch (CPU/GPU)"),
                    ("vllm", "Local vLLM Container"),
                    ("ollama", "Local Ollama Container"),
                ],
                default="pytorch",
                help_text="Select the primary inference engine used by the local proxy server.",
                max_length=20,
            ),
        ),
    ]
