# Generated by Django 6.0.7 on 2026-07-14 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0014_alter_systemconfiguration_active_ollama_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemconfiguration",
            name="vllm_endpoint",
        ),
    ]
