# Generated by Django 6.0.7 on 2026-07-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0015_remove_systemconfiguration_vllm_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponselog",
            name="generation_duration_ms",
            field=models.FloatField(
                blank=True,
                help_text="Total wall-clock duration of the generation call in milliseconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="promptresponselog",
            name="tokens_per_second",
            field=models.FloatField(
                blank=True, help_text="Output tokens generated per second", null=True
            ),
        ),
    ]
