# Generated by Django 6.0.7 on 2026-07-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0016_promptresponselog_generation_duration_ms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="state_tree",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Hierarchical task and topic tracking tree (WS7).",
                null=True,
            ),
        ),
    ]
