# Generated by Django 6.0.7 on 2026-07-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0017_conversation_state_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponselog",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="The AI model used for this generation",
                max_length=255,
                null=True,
            ),
        ),
    ]
