# Generated by Django 6.0.8 on 2026-08-12 03:02

import django.db.models.deletion
from django.db import migrations, models


def migrate_system_tokenizer(apps, schema_editor):
    SystemConfiguration = apps.get_model("llm_api", "SystemConfiguration")
    LocalAIModel = apps.get_model("llm_api", "LocalAIModel")
    
    config = SystemConfiguration.objects.first()
    if config and config.old_system_tokenizer_id:
        hf_id = config.old_system_tokenizer_id
        model_obj, created = LocalAIModel.objects.get_or_create(
            hf_model_id=hf_id,
            defaults={"name": hf_id, "description": "Auto-created from old system_tokenizer_id"}
        )
        config.system_tokenizer = model_obj
        config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0018_promptresponselog_model_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemconfiguration",
            name="system_tokenizer_id",
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="old_system_tokenizer_id",
            field=models.CharField(
                default="Qwen/Qwen2.5-3B-Instruct",
                help_text="TEMP field for migration",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="system_tokenizer",
            field=models.ForeignKey(
                blank=True,
                help_text="Loaded into CPU RAM to count tokens, even if local VRAM model is disabled.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_tokenizer_configurations",
                to="llm_api.localaimodel",
            ),
        ),
        migrations.RunPython(migrate_system_tokenizer),
        migrations.RemoveField(
            model_name="systemconfiguration",
            name="old_system_tokenizer_id",
        ),
    ]
