# Generated by Django 6.0.8 on 2026-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0019_remove_systemconfiguration_system_tokenizer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptresponselog",
            name="state_tree_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of the conversation state_tree at this turn.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localaimodel",
            name="name",
            field=models.CharField(
                help_text="Friendly name (e.g. 'Gemma 4 E2B')", max_length=255
            ),
        ),
    ]
