# Generated by Django 6.0.8 on 2026-09-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0020_promptresponselog_state_tree_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localaimodel",
            name="compute_dtype",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-detect (Recommended based on GPU capability)"),
                    ("float16", "Float16 (FP16)"),
                    ("bfloat16", "BFloat16 (BF16 - requires Ampere / CC 8.0+)"),
                    ("float32", "Float32 (FP32 - CPU fallback)"),
                ],
                default="auto",
                help_text="Precision used for tensor computations.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="localaimodel",
            name="quantization_mode",
            field=models.CharField(
                choices=[
                    ("none", "Unquantized (16-bit FP16 / BF16)"),
                    ("int8", "8-bit Integer (BitsAndBytes)"),
                    ("nf4", "4-bit NormalFloat (BitsAndBytes NF4 - High Precision)"),
                    ("fp4", "4-bit Float (BitsAndBytes FP4)"),
                    ("awq", "AWQ (vLLM / Transformers)"),
                    ("gptq", "GPTQ (vLLM / Transformers)"),
                ],
                default="nf4",
                help_text="Quantization method to apply when loading model into memory or container.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="localaimodel",
            name="vllm_gpu_memory_utilization",
            field=models.FloatField(
                blank=True,
                help_text="vLLM GPU memory utilization fraction (0.1 - 1.0). Leave blank to auto-calculate from free VRAM.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="localaimodel",
            name="vllm_max_model_len",
            field=models.IntegerField(
                blank=True,
                help_text="Max model sequence length for vLLM KV-cache. Defaults to model context window.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localaimodel",
            name="load_in_4bit",
            field=models.BooleanField(
                default=True,
                help_text="Legacy flag: Use 4-bit quantization (synced with quantization_mode)",
            ),
        ),
    ]
