# Generated by Django 6.1.1 on 2026-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0021_localaimodel_compute_dtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalaimodel",
            name="is_multimodal",
            field=models.BooleanField(
                default=False,
                help_text="Whether this external API endpoint supports visual/multimodal inputs.",
            ),
        ),
        migrations.AddField(
            model_name="localaimodel",
            name="is_multimodal",
            field=models.BooleanField(
                default=False,
                help_text="Whether this model architecture supports visual/multimodal inputs.",
            ),
        ),
    ]
