[pytest]
DJANGO_SETTINGS_MODULE = verbal_config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --doctest-modules --doctest-glob="*.rst"
norecursedirs = workspaces sandbox .git .idea .pytest_cache .agents