# Generated by Django 5.2.7 on 2026-03-17 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CognitiveBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Describes when the Router should select this blueprint.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReasoningStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Draft Hypothesis', 'Critique Draft'",
                        max_length=255,
                    ),
                ),
                (
                    "is_start_node",
                    models.BooleanField(
                        default=False,
                        help_text="Check this if this is the first step in the blueprint.",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="The prompt driving this step of the thought process."
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Optional: What defines a 'success' for this step? Used by the LLM-as-a-judge to decide whether to follow the success or failure edge.",
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="metacognition.cognitiveblueprint",
                    ),
                ),
                (
                    "on_failure_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="The step to route to if this step fails its evaluation criteria.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failure_sources",
                        to="metacognition.reasoningstep",
                    ),
                ),
                (
                    "on_success_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="The next step if this step completes successfully.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="success_sources",
                        to="metacognition.reasoningstep",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
