# Generated by Django 5.2.7 on 2026-04-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModerationList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "concepts",
                    models.TextField(
                        help_text="Comma-separated concepts (lemmas). E.g., 'arson, bomb, explosive'"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("json", "JSON Schema"),
                            ("pydantic", "Hardcoded Pydantic Model"),
                        ],
                        default="json",
                        max_length=20,
                    ),
                ),
                (
                    "json_schema",
                    models.TextField(
                        blank=True,
                        help_text='Enter valid JSON Schema. Example for a simple string wrapper:\n{\n  "type": "object",\n  "properties": {\n    "result": {"type": "string"}\n  },\n  "required": ["result"]\n}',
                    ),
                ),
                (
                    "pydantic_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of a registered model (e.g., 'Hydrant', 'Factor'). Must exist in llm_api.api.OUTPUT_TYPES.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Describes when the Router should select this blueprint.",
                    ),
                ),
                (
                    "moderation_lists",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Reusable moderation rules applied to all steps in this blueprint.",
                        to="metacognition.moderationlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReasoningStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Draft Hypothesis', 'Critique Draft'",
                        max_length=255,
                    ),
                ),
                (
                    "is_start_node",
                    models.BooleanField(
                        default=False,
                        help_text="Check this if this is the first step in the blueprint.",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="The prompt driving this step of the thought process."
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Optional: What defines a 'success' for this step? Used by the LLM-as-a-judge to decide whether to follow the success or failure edge.",
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="metacognition.cognitiveblueprint",
                    ),
                ),
                (
                    "on_failure_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="The step to route to if this step fails its evaluation criteria.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failure_sources",
                        to="metacognition.reasoningstep",
                    ),
                ),
                (
                    "on_success_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="The next step if this step completes successfully.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="success_sources",
                        to="metacognition.reasoningstep",
                    ),
                ),
                (
                    "output_schema",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a structured output format for this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metacognition.responseschema",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
