# Generated by Django 5.2.7 on 2026-05-02 00:49

import metacognition.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responseschema",
            name="pydantic_model_name",
            field=models.CharField(
                blank=True,
                choices=metacognition.models.get_schema_choices,
                help_text="Name of a registered model (e.g. 'Factor'). Sourced from registered OUTPUT_TYPES.",
                max_length=255,
            ),
        ),
    ]
