# Generated by Django 5.2.7 on 2026-03-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "concepts",
                    models.TextField(
                        help_text="Comma-separated concepts (lemmas). E.g., 'arson, bomb, explosive'"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("json", "JSON Schema"),
                            ("pydantic", "Hardcoded Pydantic Model"),
                        ],
                        default="json",
                        max_length=20,
                    ),
                ),
                (
                    "json_schema",
                    models.TextField(
                        blank=True,
                        help_text='Enter valid JSON Schema. Example for a simple string wrapper:\n{\n  "type": "object",\n  "properties": {\n    "result": {"type": "string"}\n  },\n  "required": ["result"]\n}',
                    ),
                ),
                (
                    "pydantic_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of a registered model (e.g., 'Hydrant', 'Factor'). Must exist in llm_api.api.OUTPUT_TYPES.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cognitiveblueprint",
            name="moderation_lists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reusable moderation rules applied to all steps in this blueprint.",
                to="metacognition.moderationlist",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="output_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a structured output format for this step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metacognition.responseschema",
            ),
        ),
    ]
