# Generated by Django 5.2.7 on 2026-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0002_alter_responseschema_pydantic_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="action_hook",
            field=models.CharField(
                blank=True,
                help_text="Optional: Name of a Python function to run after LLM generation (e.g., 'handle_active_reading').",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="max_retries",
            field=models.IntegerField(
                default=3,
                help_text="Maximum times this step can loop before forcing a failure.",
            ),
        ),
    ]
