# Generated by Django 6.0.5 on 2026-06-02 00:52

import metacognition.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0003_reasoningstep_action_hook_reasoningstep_max_retries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reasoningstep",
            name="action_hook",
            field=models.CharField(
                blank=True,
                choices=metacognition.models.get_action_choices,
                help_text="Optional: Name of a Python Action Hook to intercept and execute tools from the LLM's output.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="reasoningstep",
            name="system_prompt",
            field=models.TextField(
                help_text="The prompt driving this step. For a pre-written plan, instruct the LLM to output a specific sequence of tools in the ExecutionPlan."
            ),
        ),
    ]
