# Generated by Django 6.0.5 on 2026-06-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0004_alter_reasoningstep_action_hook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="sub_blueprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Execute another blueprint as a sub-routine before moving to the next step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoked_by_steps",
                to="metacognition.cognitiveblueprint",
            ),
        ),
    ]
