# Generated by Django 6.0.6 on 2026-06-23 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0005_reasoningstep_sub_blueprint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="parallel_steps",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: Execute these steps in parallel (fan-out) upon success.",
                related_name="parallel_sources",
                to="metacognition.reasoningstep",
            ),
        ),
        migrations.CreateModel(
            name="AgentCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(db_index=True, max_length=255)),
                ("checkpoint_id", models.CharField(db_index=True, max_length=255)),
                ("parent_id", models.CharField(blank=True, max_length=255, null=True)),
                ("state_json", models.JSONField(default=dict)),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("thread_id", "checkpoint_id")},
            },
        ),
        migrations.CreateModel(
            name="ToolDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("builtin", "Built-in Python Function"),
                            ("api", "HTTP API Call"),
                            ("blueprint", "Execute Sub-Blueprint"),
                            ("django_action", "Django ORM Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("python_path", models.CharField(blank=True, max_length=500)),
                ("api_url", models.URLField(blank=True)),
                (
                    "input_schema",
                    models.TextField(
                        blank=True, help_text="JSON Schema for tool parameters"
                    ),
                ),
                (
                    "output_schema",
                    models.TextField(
                        blank=True, help_text="JSON Schema for tool return value"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="If true, triggers human-in-the-loop before execution",
                    ),
                ),
                (
                    "is_promoted",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this tool has been promoted to production and is fully available.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_blueprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_definitions",
                        to="metacognition.cognitiveblueprint",
                    ),
                ),
            ],
        ),
    ]
