# Generated by Django 6.0.6 on 2026-06-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0008_seed_architect_blueprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="parent_step",
            field=models.ForeignKey(
                blank=True,
                help_text="The ancestral ReasoningStep this variant evolved from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="metacognition.reasoningstep",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="performance_score",
            field=models.FloatField(
                default=0.0,
                help_text="Calculated periodically by the NightManager (e.g. success rate discount).",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="selection_weight",
            field=models.FloatField(
                default=1.0,
                help_text="Weight used for A/B testing or RL multi-armed bandit variant selection.",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="variant_intent",
            field=models.CharField(
                blank=True,
                help_text="What this speciated variant is optimized for (e.g. 'Spatial Execution').",
                max_length=255,
            ),
        ),
    ]
