# Generated by Django 6.0.6 on 2026-06-24 11:32

from django.db import migrations




def seed_nightmanager(apps, schema_editor):
    CognitiveBlueprint = apps.get_model('metacognition', 'CognitiveBlueprint')
    ReasoningStep = apps.get_model('metacognition', 'ReasoningStep')
    ResponseSchema = apps.get_model('metacognition', 'ResponseSchema')

    # Ensure schema exists
    schema_variant, _ = ResponseSchema.objects.get_or_create(
        name="PromptVariant_Schema", 
        defaults={'schema_type': 'pydantic', 'pydantic_model_name': 'PromptVariant'}
    )

    bp, _ = CognitiveBlueprint.objects.get_or_create(
        name="NightManager: Evaluate Prompts",
        defaults={
            'description': "Evaluates failing ReasoningSteps and generates highly optimized variant prompts."
        }
    )

    ReasoningStep.objects.get_or_create(
        blueprint=bp,
        name="DraftNewPrompt",
        defaults={
            'is_start_node': True,
            'system_prompt': "You are The Architect, an elite prompt engineer. Review the provided failure logs and the original system prompt for a cognitive agent node. The agent consistently failed or got trapped in loops. Analyze the root cause of the misunderstanding. Draft a highly optimized replacement system prompt that specifically prevents these failures while maintaining the core objective. Your goal is to speciate a more robust variant.",
            'action_hook': "create_prompt_variant",
            'output_schema': schema_variant,
            'max_retries': 3
        }
    )

class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0009_reasoningstep_parent_step_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_nightmanager, reverse_code=migrations.RunPython.noop),
    ]
