# Generated by Django 6.0.6 on 2026-06-26 01:06

from django.db import migrations

def run_seed_all(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0010_seed_nightmanager_blueprint"),
    ]

    operations = [
        migrations.RunPython(run_seed_all, reverse_code=migrations.RunPython.noop),
    ]
