# Generated by Django 6.0.6 on 2026-06-29 03:44

import metacognition.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0011_centralize_seeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="available_tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tools available to the LLM during this step.",
                related_name="reasoning_steps",
                to="metacognition.tooldefinition",
            ),
        ),
        migrations.AlterField(
            model_name="reasoningstep",
            name="action_hook",
            field=models.CharField(
                blank=True,
                help_text="[DEPRECATED] Use available_tools instead.",
                max_length=255,
            ),
        ),
    ]
