# Generated by Django 6.0.6 on 2026-06-29 03:44

from django.db import migrations


def migrate_hooks_to_tools(apps, schema_editor):
    ReasoningStep = apps.get_model('metacognition', 'ReasoningStep')
    ToolDefinition = apps.get_model('metacognition', 'ToolDefinition')
    
    for step in ReasoningStep.objects.exclude(action_hook=''):
        tool, created = ToolDefinition.objects.get_or_create(
            name=step.action_hook,
            defaults={
                'description': f'Auto-migrated tool for {step.action_hook}',
                'tool_type': 'django_action',
                'python_path': f'metacognition.actions.{step.action_hook}',
            }
        )
        step.available_tools.add(tool)

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0012_reasoningstep_available_tools_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_hooks_to_tools, reverse_migration),
    ]
