# Generated by Django 6.0.6 on 2026-06-29 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0013_migrate_action_hooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reasoningstep",
            name="action_hook",
        ),
    ]
