# Generated by Django 6.0.6 on 2026-06-29 03:59

from django.db import migrations


def run_seed_all(apps, schema_editor):
    from metacognition.seed import seed_all
    seed_all()

class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0014_remove_reasoningstep_action_hook"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
