# Generated by Django 6.0.6 on 2026-07-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0015_reseed_pipelines"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="max_new_tokens",
            field=models.IntegerField(
                default=500,
                help_text="Maximum tokens to generate for this step. Increase for long-form analysis, decrease for short routing decisions.",
            ),
        ),
    ]
