# Generated by Django 6.0.6 on 2026-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0016_reasoningstep_max_new_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveblueprint",
            name="is_autonomous",
            field=models.BooleanField(
                default=False,
                help_text="If True, self-routing on failure (route_to=SELF) is handled automatically rather than pausing for user input.",
            ),
        ),
    ]
