# Generated by Django 6.0.6 on 2026-07-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0010_loraadapter_and_more"),
        ("metacognition", "0017_cognitiveblueprint_is_autonomous"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveblueprint",
            name="lora_adapter",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional specialized LoRA weights to load when running this blueprint.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="llm_api.loraadapter",
            ),
        ),
    ]
