# Generated by Django 6.0.7 on 2026-07-15 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_api", "0015_remove_systemconfiguration_vllm_endpoint"),
        ("metacognition", "0018_cognitiveblueprint_lora_adapter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cognitiveblueprint",
            name="lora_adapter",
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Set to False to soft-delete a bad leaf node variant while retaining it for historical tracking.",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="lora_adapter",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional specialized LoRA weights to load when running this specific step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="llm_api.loraadapter",
            ),
        ),
    ]
