# Generated by Django 6.0.7 on 2026-07-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0019_remove_cognitiveblueprint_lora_adapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveblueprint",
            name="is_canonical",
            field=models.BooleanField(
                default=False,
                help_text="If True, this object is maintained by seed.py and cannot be mutated.",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="is_canonical",
            field=models.BooleanField(
                default=False,
                help_text="If True, this object is maintained by seed.py and cannot be mutated.",
            ),
        ),
    ]
