# Generated by Django 6.0.7 on 2026-07-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0020_cognitiveblueprint_is_canonical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveblueprint",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The Blueprint this was cloned from, for lineage tracking.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="descendants",
                to="metacognition.cognitiveblueprint",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="is_pending_review",
            field=models.BooleanField(
                default=False,
                help_text="Set by NightManager when proposing a new variant for human review.",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="proposed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="proposed_by",
            field=models.CharField(
                choices=[("system", "System"), ("user", "User")],
                default="user",
                max_length=20,
            ),
        ),
    ]
