# Generated by Django 6.0.8 on 2026-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0021_cognitiveblueprint_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="include_state_tree",
            field=models.BooleanField(
                default=True,
                help_text="If True, formats and injects Conversation.state_tree into the working prompt.",
            ),
        ),
    ]
