# Generated by Django 6.1.1 on 2026-10-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0023_tooldefinition_governance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoningstep",
            name="deterministic_tool",
            field=models.ForeignKey(
                blank=True,
                help_text="The tool to execute deterministically when execution_mode='pure_tool'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deterministic_steps",
                to="metacognition.tooldefinition",
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("llm", "LLM Generation (Prompt + Optional Tools)"),
                    ("pure_tool", "Deterministic Tool Execution (No LLM Call)"),
                ],
                default="llm",
                help_text="In 'pure_tool' mode, deterministic_tool executes immediately without calling the LLM.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reasoningstep",
            name="tool_args_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Declarative parameter mapping, e.g. {'query': '$user_prompt'} or {'query': '$state_tree.active_task'}.",
            ),
        ),
        migrations.AlterField(
            model_name="reasoningstep",
            name="max_new_tokens",
            field=models.IntegerField(
                default=1500,
                help_text="Maximum tokens to generate for this step. Increase for long-form analysis, decrease for short routing decisions.",
            ),
        ),
        migrations.AlterField(
            model_name="reasoningstep",
            name="system_prompt",
            field=models.TextField(
                blank=True,
                help_text="The prompt driving this step. For a pre-written plan, instruct the LLM to output a specific sequence of tools in the ExecutionPlan.",
            ),
        ),
    ]
