# Generated by Django 6.1.1 on 2026-10-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacognition", "0024_reasoningstep_deterministic_tool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveblueprint",
            name="category",
            field=models.CharField(
                choices=[
                    ("REASONING", "Conversational Reasoning"),
                    ("GRIPS", "Grips Knowledge Graph"),
                    ("SYSTEM", "System Infrastructure"),
                ],
                db_index=True,
                default="REASONING",
                help_text="Discriminates user-facing conversational reasoning blueprints from Grips maintenance and background system routines.",
                max_length=50,
            ),
        ),
    ]
