# Generated by Django 5.2.7 on 2026-04-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("llm_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Celery Status Dashboard",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Broad description of this knowledge domain."
                    ),
                ),
                (
                    "style_guide",
                    models.TextField(
                        blank=True,
                        help_text='Instructions for the LLM on how to format or reason about concepts in this domain. <a href="/static/docs/style_guides.html" target="_blank">View the style guide docs</a>.',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used for internal [[wiki-linking]]", unique=True
                    ),
                ),
                (
                    "focus_hint",
                    models.CharField(
                        blank=True,
                        help_text="Optional hint to disambiguate the topic for the AI (e.g., 'Focus purely on physical extrication, not vehicle deployment').",
                        max_length=500,
                    ),
                ),
                (
                    "narrative_content",
                    models.TextField(
                        blank=True,
                        help_text='The dense, Markdown-formatted explanation. <a href="/static/docs/markdown_tips.html" target="_blank">Markdown Tips & Tricks</a>',
                        null=True,
                    ),
                ),
                (
                    "structured_claims",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of atomic claims (e.g., [{'subject': 'A', 'predicate': 'is', 'object': 'B'}]) for programmatic linting.",
                        null=True,
                    ),
                ),
                (
                    "needs_linting",
                    models.BooleanField(
                        default=True,
                        help_text="Flagged when updated so the background linter can verify it.",
                    ),
                ),
                ("last_linted_at", models.DateTimeField(blank=True, null=True)),
                ("linting_report", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="grips.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptRecipies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "system_prompt_template",
                    models.TextField(
                        help_text="Template injecting Domain context. Use {{ concepts }} to inject retrieved ConceptNodes."
                    ),
                ),
                (
                    "needs_linting",
                    models.BooleanField(
                        default=True,
                        help_text="Flagged when updated so the background linter can verify it.",
                    ),
                ),
                ("last_linted_at", models.DateTimeField(blank=True, null=True)),
                ("linting_report", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harnesses",
                        to="grips.domain",
                    ),
                ),
                (
                    "recommended_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="The model this harness was optimized for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="llm_api.localaimodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("DEPENDS_ON", "Depends On (Causal / Prerequisite)"),
                            ("INCLUDES", "Includes / Comprises (Part-Whole)"),
                            (
                                "EXEMPLIFIES",
                                "Exemplifies / Instantiates (Idea-Example)",
                            ),
                            (
                                "RELATED_TO",
                                "Is Related To (Catchall) - alternatives, constraints, exclusions, negations",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Explanation for the relatioship or specific catchall relationship (e.g., is_alternative_to)",
                    ),
                ),
                (
                    "needs_linting",
                    models.BooleanField(
                        default=True,
                        help_text="Flagged when updated so the background linter can verify it.",
                    ),
                ),
                ("last_linted_at", models.DateTimeField(blank=True, null=True)),
                ("linting_report", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="grips.conceptnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="grips.conceptnode",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "target", "relationship_type")},
            },
        ),
    ]
