# Generated by Django 5.2.7 on 2026-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0001_initial"),
        ("grips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents that form the foundational knowledge corpus for this domain.",
                related_name="domains",
                to="background_resources.document",
            ),
        ),
    ]
