# Generated by Django 6.0.5 on 2026-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grips", "0002_domain_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptnode",
            name="slug",
            field=models.SlugField(
                help_text="Used for internal [[wiki-linking]]",
                max_length=255,
                unique=True,
            ),
        ),
    ]
