# Generated by Django 6.0.5 on 2026-05-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0002_grobidreadingstrategy"),
        ("grips", "0003_alter_conceptnode_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptnode",
            name="source_chunk",
            field=models.ForeignKey(
                blank=True,
                help_text="The Primary RAGChunk which is summarised in this concept.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sourced_concepts",
                to="background_resources.ragchunk",
            ),
        ),
    ]
