# Generated by Django 6.0.6 on 2026-07-03 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grips", "0004_conceptnode_source_chunk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PromptRecipies",
        ),
    ]
