# Generated by Django 6.0.8 on 2026-08-06 05:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grips", "0005_delete_promptrecipies"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptnode",
            name="issue_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("needs_citation", "Needs Citation"),
                        ("style_violation", "Style Violation"),
                        ("needs_clarification", "Needs Clarification"),
                        ("orphaned", "Orphaned (Missing Links)"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="Wikipedia-style issue tags indicating problems with the narrative.",
            ),
        ),
    ]
