# Generated by Django 6.0.8 on 2026-08-14 02:09

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "background_resources",
            "0004_ragchunk_embedding_ragchunk_ragchunk_embed_hnsw",
        ),
        ("grips", "0006_conceptnode_issue_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptnode",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="conceptnode",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="conceptnode_embed_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
