# Generated by Django 5.2.7 on 2025-11-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField()),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("unstructured", "Unstructured"),
                            ("line_separated", "Lines / Rows"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
