# Generated by Django 5.2.7 on 2026-03-03 04:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Original author or organization",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "citation_text",
                    models.TextField(
                        blank=True, help_text="APA/MLA citation string", null=True
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "indexed_hash",
                    models.TextField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("chunk_size", models.IntegerField(default=1000)),
                ("chunk_overlap", models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name="RAGChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_id",
                    models.CharField(db_index=True, max_length=36, unique=True),
                ),
                ("text_content", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "in_vector_index",
                    models.BooleanField(
                        default=False, help_text="Is this chunk indexed in FAISS?"
                    ),
                ),
                (
                    "in_byte_store",
                    models.BooleanField(
                        default=False,
                        help_text="Is the full object stored in the ByteStore?",
                    ),
                ),
                ("hit_count", models.IntegerField(default=0)),
                (
                    "last_accessed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RAGQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user_feedback_score",
                    models.IntegerField(
                        blank=True, help_text="1 to 5 or -1/1", null=True
                    ),
                ),
                ("response_generated", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AbbreviationsReadingStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("strategy_description", models.CharField(max_length=255)),
                (
                    "chunk_size_override",
                    models.IntegerField(
                        blank=True,
                        help_text="If set, re-chunks document for this reading",
                        null=True,
                    ),
                ),
                ("chunk_overlap_override", models.IntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="background_resources.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VectorIndexExplorer",
            fields=[],
            options={
                "verbose_name": "Vector Index Explorer",
                "verbose_name_plural": "Vector Index Explorer",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("background_resources.document",),
        ),
        migrations.CreateModel(
            name="PromptStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("strategy_description", models.CharField(max_length=255)),
                (
                    "chunk_size_override",
                    models.IntegerField(
                        blank=True,
                        help_text="If set, re-chunks document for this reading",
                        null=True,
                    ),
                ),
                ("chunk_overlap_override", models.IntegerField(blank=True, null=True)),
                (
                    "prompt",
                    models.TextField(
                        default="Prompt to use the AI service to generate key text to find this chunk - summaries, keywords, hypothetical questions etc. The chunk text is appended to this prompt with whatever intro you put in this prompt."
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="background_resources.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReadingStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_chunking",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("strategy_description", models.CharField(max_length=255)),
                (
                    "chunk_size_override",
                    models.IntegerField(
                        blank=True,
                        help_text="If set, overrides document default",
                        null=True,
                    ),
                ),
                ("chunk_overlap_override", models.IntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="background_resources.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegexStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("strategy_description", models.CharField(max_length=255)),
                (
                    "chunk_size_override",
                    models.IntegerField(
                        blank=True,
                        help_text="If set, re-chunks document for this reading",
                        null=True,
                    ),
                ),
                ("chunk_overlap_override", models.IntegerField(blank=True, null=True)),
                (
                    "strategy_details",
                    models.TextField(
                        default="The default glossary grabber - splits lines at colon or hyphen, captures two groups, the indexed text and the corresponding body. Your regex must capture two groups."
                    ),
                ),
                (
                    "regex",
                    models.TextField(
                        default="(.+?)(?:\\s*:(?!\\/\\/)\\s*|\\s*-\\s+)([^\\n\\r]+)"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="background_resources.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZeroShotLabelReadingStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("strategy_description", models.CharField(max_length=255)),
                (
                    "chunk_size_override",
                    models.IntegerField(
                        blank=True,
                        help_text="If set, re-chunks document for this reading",
                        null=True,
                    ),
                ),
                ("chunk_overlap_override", models.IntegerField(blank=True, null=True)),
                (
                    "prompt",
                    models.TextField(
                        default="Generate a label for each of these chunks based on the context provided."
                    ),
                ),
                ("label_options", models.JSONField(default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="background_resources.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyChunkUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("REUSED", "Reused (Reused Store Content)"),
                            ("CLIPPED", "Clipped (Verbatim Document Content)"),
                            (
                                "CREATED",
                                "Created (Synthetic / Semantic Document Content)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="background_resources.ragchunk",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("chunk", "content_type", "object_id", "role")},
            },
        ),
    ]
