# Generated by Django 5.2.7 on 2026-03-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="currently_indexed",
            field=models.BooleanField(default=False),
        ),
    ]
