# Generated by Django 5.2.7 on 2026-05-11 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrobidReadingStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "strategy_description",
                    models.CharField(
                        default="Grobid Semantic Chunking", max_length=255
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="background_resources.document",
                    ),
                ),
            ],
        ),
    ]
