# Generated by Django 5.2.7 on 2025-11-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="doc_type",
        ),
        migrations.AddField(
            model_name="document",
            name="chunk_overlap",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="document",
            name="chunk_size",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="document",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
