# Generated by Django 5.2.7 on 2025-12-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "background_resources",
            "0002_remove_document_doc_type_document_chunk_overlap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="indexing_strategy",
            field=models.CharField(
                choices=[
                    ("RAW", "Standard (Match query to similar text)"),
                    (
                        "SUM",
                        "Conceptual (Match query to pre-processed summary of source text)",
                    ),
                ],
                default="RAW",
                max_length=3,
                verbose_name="Search Optimization Mode",
            ),
        ),
    ]
