# Generated by Django 6.0.7 on 2026-07-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0002_grobidreadingstrategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragchunk",
            name="in_vector_index",
            field=models.BooleanField(
                default=False, help_text="Is this chunk indexed in PGVector?"
            ),
        ),
    ]
