# Generated by Django 6.0.8 on 2026-08-14 02:09

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0003_alter_ragchunk_in_vector_index"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name="ragchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="ragchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="ragchunk_embed_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
