# Generated by Django 5.2.7 on 2025-12-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0003_document_indexing_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorIndexExplorer",
            fields=[],
            options={
                "verbose_name": "Vector Index Explorer",
                "verbose_name_plural": "Vector Index Explorer",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("background_resources.document",),
        ),
        migrations.AddField(
            model_name="document",
            name="currently_indexed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="indexing_strategy",
            field=models.CharField(
                choices=[
                    ("RAW", "Standard (Match query to similar text)"),
                    (
                        "SUM",
                        "Conceptual (Match query to pre-processed summary of source text)",
                    ),
                    (
                        "DIC",
                        "Match query elements to terms in glossary or dictionary and return definition",
                    ),
                ],
                default="RAW",
                max_length=3,
                verbose_name="Search Optimization Mode",
            ),
        ),
    ]
