# Generated by Django 6.1.1 on 2026-10-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "background_resources",
            "0004_ragchunk_embedding_ragchunk_ragchunk_embed_hnsw",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("ACADEMIC_PAPER", "Academic Paper"),
                    ("STANDARD_OR_REGULATION", "Standard / Regulation"),
                    ("TECHNICAL_MANUAL", "Technical Manual"),
                    ("GLOSSARY", "Glossary / Dictionary"),
                    ("NOTEBOOK_OR_CODE", "Notebook / Code"),
                    ("GENERAL", "General Document"),
                ],
                default="GENERAL",
                help_text="Category of source document",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="Digital Object Identifier",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Publishing organization or institution, e.g. NFPA, NIST, IEEE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="publication_year",
            field=models.CharField(
                blank=True,
                help_text="Publication year or span, e.g. 2023 or 2022-2024",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="Original author or individual contributor",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="publication_date",
            field=models.DateField(
                blank=True, help_text="Exact publication date if known", null=True
            ),
        ),
    ]
