# Generated by Django 5.2.7 on 2026-01-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "background_resources",
            "0004_vectorindexexplorer_document_currently_indexed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_regex",
            field=models.CharField(
                blank=True,
                help_text="Optional regex for extracting terms (group 1) and definitions (group 2). If provided, this overrides LLM extraction.",
                max_length=512,
                null=True,
            ),
        ),
    ]
