# Generated by Django 6.1.1 on 2026-10-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0005_document_document_type_document_doi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragchunk",
            name="chunk_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text Paragraph"),
                    ("FIGURE", "Figure / Image"),
                    ("TABLE", "Data Table"),
                    ("GLOSSARY", "Glossary Definition"),
                ],
                db_index=True,
                default="TEXT",
                help_text="Structural category of chunk",
                max_length=20,
            ),
        ),
    ]
