"""
Django settings for verbal_config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

VERBAL_ENV = os.environ.get("VERBAL_ENV", "dev")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-di_unz7h49exp@-(oyl0i2v8i-7%-zr@8c@ejl%!%f6b=-vh8-")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = VERBAL_ENV == "dev"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "background_resources.apps.BackgroundResourcesConfig",
    "benchmarking.apps.BenchmarkingConfig",
    "llm_api.apps.LlmApiConfig",
    "metacognition.apps.MetacognitionConfig",
    'grips.apps.GripsConfig',
    'grobid_client.apps.GrobidClientConfig',
    'demo_ui.apps.DemoUiConfig',
    'django_celery_beat',
    'sandbox_manager.apps.SandboxManagerConfig',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "verbal_config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "verbal_config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("DB_NAME", "verbal_db"),
        "USER": os.environ.get("DB_USER", "verbal_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "verbal_password"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5433"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Australia/Melbourne"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Test runner
TEST_RUNNER = 'verbal.test_runner.ForceTeardownTestRunner'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FILES = BASE_DIR / 'background_resources/knowledge_sources/'
VECTOR_STORE = BASE_DIR / 'background_resources/vector_store/'
CHUNK_STORE = BASE_DIR / 'background_resources/vector_store/chunks/'
DEFINITION_STORE = BASE_DIR / 'background_resources/vector_store/definitions/'

# LLM models that are solid condidates as per early 2026 for my development machine with only 6gb VRAM
# LLM_MODEL_ID = "microsoft/Phi-3-mini-4k-instruct"
# LLM_MODEL_ID = "Qwen/Qwen2.5-3B-Instruct"  # Highly recommended for 6GB VRAM
# LLM_MODEL_ID = "google/gemma-2-2b-it"      # Very fast, lightweight
# LLM_MODEL_ID = "mistralai/Mistral-7B-Instruct-v0.3" # Might be tight/slow
# LLM_MODEL_ID = "meta-llama/Meta-Llama-3.1-8B-Instruct" # Likely to OOM on 6GB

# LLM models that are solid condidates as per early 2026 for a better machine with 16gb VRAM
# Qwen 2.5 14B Instruct (Quantized): Highly Recommended. If you run this through Ollama (ollama run qwen2.5:14b), it will use 4-bit quantization and take up about 9GB of VRAM. It punches so far above its weight class that it rivals GPT-4o-mini in logic, coding, and JSON constraint adherence. It is the absolute champion of this tier.
# Llama 3.1 8B Instruct (Unquantized): If you want to run natively in your inference Django instance without aggressive quantization, this is the way to go. It will take about 10GB of VRAM in FP16, leaving you 6GB for a massive KV-cache (meaning it can read entire RAG chunks simultaneously without breaking a sweat).

#Mistral NeMo 12B: Co-developed by Nvidia, this model was practically designed for your GPU. It has a massive 128k context window natively and is explicitly trained for RAG retrieval tasks.

# ------------------------------------------------------------------------
# MICROSERVICE / ROLE CONFIGURATION
# ------------------------------------------------------------------------
# Roles: 'standalone' (loads model), 'inference' (loads model), 'web' (HTTP client), 'worker' (HTTP client)
VERBAL_ROLE = os.environ.get("VERBAL_ROLE", "standalone")

# If acting as a web/worker client, where is the inference server?
INFERENCE_URL = os.environ.get("INFERENCE_URL", "http://127.0.0.1:8001/api/llm")

# Base URLs for external containerized inference endpoints
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://127.0.0.1:11434")
VLLM_BASE_URL = os.environ.get("VLLM_BASE_URL", "http://127.0.0.1:8003")

# ------------------------------------------------------------------------
# CELERY & REDIS CONFIGURATION
# ------------------------------------------------------------------------

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
SANDBOX_URL="http://127.0.0.1:8002/execute"   # if django were dockerised, use docker dns "http://sandbox:8000/execute"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "llm_api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "metacognition": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "demo_ui": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "background_resources": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "benchmarking": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "grips": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}