# Generated by Django 6.0.8 on 2026-08-31 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "task_path",
                    models.CharField(
                        help_text="Dotted python import path to the task function",
                        max_length=255,
                    ),
                ),
                (
                    "queue_name",
                    models.CharField(db_index=True, default="default", max_length=64),
                ),
                ("priority", models.IntegerField(db_index=True, default=0)),
                ("args_json", models.JSONField(blank=True, default=list)),
                ("kwargs_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="READY",
                        max_length=32,
                    ),
                ),
                (
                    "enqueued_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "run_after",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("return_value_json", models.JSONField(blank=True, null=True)),
                ("error_traceback", models.TextField(blank=True, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "verbose_name": "Task Record",
                "verbose_name_plural": "Task Records",
                "ordering": ["-priority", "enqueued_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "queue_name", "priority", "enqueued_at"],
                        name="verbal_task_status_d38566_idx",
                    ),
                    models.Index(
                        fields=["status", "run_after"],
                        name="verbal_task_status_8ee22b_idx",
                    ),
                ],
            },
        ),
    ]
