# Generated by Django 6.0.8 on 2026-08-31 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verbal_tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique label for this scheduled task",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Dotted import path to the @task function (e.g. 'metacognition.tasks.task_run_blueprint_async')",
                        max_length=255,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Standard 5-field cron expression (e.g. '0 21 * * *' for 9 PM daily)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Interval in seconds between task executions (alternative to cron)",
                        null=True,
                    ),
                ),
                (
                    "args_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of positional arguments",
                    ),
                ),
                (
                    "kwargs_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict of keyword arguments",
                    ),
                ),
                ("queue_name", models.CharField(default="default", max_length=64)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_run_count", models.PositiveIntegerField(default=0)),
                (
                    "last_task_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_triggers",
                        to="verbal_tasks.taskrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Task",
                "verbose_name_plural": "Scheduled Tasks",
                "ordering": ["name"],
            },
        ),
    ]
