# Generated by Django 6.0.8 on 2026-09-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verbal_tasks", "0002_scheduledtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrecord",
            name="duration_ms",
            field=models.FloatField(
                blank=True, help_text="Execution duration in milliseconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="input_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="Prompt/input tokens consumed by LLM calls"
            ),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="metrics_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured execution and telemetry metrics",
            ),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="output_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="Generated/output tokens from LLM calls"
            ),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="total_tokens",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Total LLM tokens consumed"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrecord",
            index=models.Index(
                fields=["status", "enqueued_at"], name="verbal_task_status_403dc0_idx"
            ),
        ),
    ]
