# Generated by Django 6.0.5 on 2026-06-04 00:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SandboxConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirements_txt",
                    models.TextField(
                        default="fastapi==0.104.1\nuvicorn==0.24.0\nnumpy\npandas\nnetworkx\npgmpy",
                        help_text="Python packages to install in the sandbox. One per line.",
                    ),
                ),
                (
                    "execution_timeout",
                    models.IntegerField(
                        default=30,
                        help_text="Maximum seconds a script can run before being killed.",
                    ),
                ),
                ("last_rebuilt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sandbox Environment Configuration",
                "verbose_name_plural": "Sandbox Environment Configuration",
            },
        ),
        migrations.CreateModel(
            name="SandboxExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("filepath", models.CharField(max_length=255)),
                (
                    "return_code",
                    models.IntegerField(
                        blank=True,
                        help_text="0 is success, >0 is error, 124 is timeout.",
                        null=True,
                    ),
                ),
                ("stdout", models.TextField(blank=True, null=True)),
                ("stderr", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
