# Generated by Django 5.2.7 on 2026-03-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("background_resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenchmarkScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "ideal_answer",
                    models.TextField(
                        help_text="The ground truth answer for semantic comparison."
                    ),
                ),
                (
                    "expected_keywords",
                    models.JSONField(
                        default=list,
                        help_text="List of strings that SHOULD be in the retrieved context.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BenchmarkCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="benchmark_corpora",
                        to="background_resources.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Benchmark Corpora",
            },
        ),
        migrations.CreateModel(
            name="BenchmarkRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("average_rag_score", models.FloatField(null=True)),
                ("average_semantic_score", models.FloatField(null=True)),
                (
                    "configuration_snapshot",
                    models.JSONField(
                        default=dict, help_text="Configuration state at time of run"
                    ),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="benchmarking.benchmarkcorpus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BenchmarkResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_text", models.TextField(default="")),
                ("raw_retrieved_text", models.TextField()),
                ("generated_response", models.TextField()),
                ("duration_seconds", models.FloatField()),
                (
                    "rag_recall_score",
                    models.FloatField(help_text="0.0 to 1.0 based on keyword hits"),
                ),
                (
                    "semantic_score",
                    models.FloatField(help_text="Cosine similarity to ideal_answer"),
                ),
                (
                    "extra_metrics",
                    models.JSONField(
                        default=dict, help_text="For future evolving metrics"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="benchmarking.benchmarkrun",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="benchmarking.benchmarkscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of settings: {'chunk_size': 500, 'model': 'gpt-4'}",
                    ),
                ),
                (
                    "iterations",
                    models.IntegerField(
                        default=1,
                        help_text="Number of times to run each scenario in the experiment.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="benchmarking.benchmarkcorpus",
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to="benchmarking.investigation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="benchmarkrun",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="benchmarking.experiment",
            ),
        ),
        migrations.CreateModel(
            name="ScenarioGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "scenarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        to="benchmarking.benchmarkscenario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experiment",
            name="scenario_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="benchmarking.scenariogroup",
            ),
        ),
    ]
