# Generated by Django 5.2.7 on 2026-03-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benchmarking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="benchmarkresult",
            name="faithfulness_score",
            field=models.FloatField(
                blank=True, help_text="1-5 score normalized to 0-1", null=True
            ),
        ),
        migrations.AddField(
            model_name="benchmarkresult",
            name="relevance_score",
            field=models.FloatField(
                blank=True, help_text="1-5 score normalized to 0-1", null=True
            ),
        ),
        migrations.AddField(
            model_name="benchmarkrun",
            name="average_faithfulness",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="benchmarkrun",
            name="average_relevance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of settings: {'chunk_size': 500, 'model': 'gpt-4'}",
            ),
        ),
    ]
