# Generated by Django 6.0.7 on 2026-07-14 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benchmarking", "0002_alter_experiment_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FineTuningDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Absolute path to the exported .jsonl file",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("sharegpt", "ShareGPT"), ("openai", "OpenAI")],
                        default="sharegpt",
                        max_length=50,
                    ),
                ),
                (
                    "scenario_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasets",
                        to="benchmarking.scenariogroup",
                    ),
                ),
            ],
        ),
    ]
