# Generated by Django 6.0.7 on 2026-07-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benchmarking", "0003_finetuningdataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="finetuningdataset",
            name="estimated_training_minutes",
            field=models.IntegerField(
                default=0, help_text="Estimated training time on typical GPU"
            ),
        ),
        migrations.AddField(
            model_name="finetuningdataset",
            name="example_count",
            field=models.IntegerField(
                default=0, help_text="Number of scenarios in dataset"
            ),
        ),
        migrations.AddField(
            model_name="finetuningdataset",
            name="semantic_diversity_score",
            field=models.FloatField(
                blank=True,
                help_text="Average cosine distance between examples (0.0 to 1.0). Higher is better.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="finetuningdataset",
            name="total_tokens",
            field=models.IntegerField(default=0, help_text="Estimated total tokens"),
        ),
        migrations.AddField(
            model_name="scenariogroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Automatically updates when modified."
            ),
        ),
    ]
