# Generated by Django 6.1.1 on 2026-09-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benchmarking", "0004_finetuningdataset_estimated_training_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finetuningdataset",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Source breakdown, filtering parameters, and dataset health metrics.",
            ),
        ),
        migrations.AddField(
            model_name="finetuningdataset",
            name="split_ratio",
            field=models.FloatField(
                default=0.85,
                help_text="Train/validation split fraction (e.g. 0.85 for 85% train, 15% validation).",
            ),
        ),
        migrations.AddField(
            model_name="finetuningdataset",
            name="train_example_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of training examples in the exported training file.",
            ),
        ),
        migrations.AddField(
            model_name="finetuningdataset",
            name="val_example_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of validation scenarios in the held-out validation group.",
            ),
        ),
        migrations.AddField(
            model_name="finetuningdataset",
            name="validation_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Held-out ScenarioGroup created automatically for post-training validation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validation_datasets",
                to="benchmarking.scenariogroup",
            ),
        ),
    ]
