# Generated by Django 5.2.7 on 2026-03-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_resources", "0002_document_currently_indexed"),
        ("benchmarking", "0004_benchmarkrun_eval_success_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="benchmarkscenario",
            name="source_chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="background_resources.ragchunk",
            ),
        ),
        migrations.AddField(
            model_name="benchmarkscenario",
            name="source_doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="background_resources.document",
            ),
        ),
    ]
