# Generated by Django 6.1.1 on 2026-10-02 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benchmarking", "0005_finetuningdataset_metadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="benchmarkrun",
            name="is_resolved",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if an environmental or codebase defect in this historical run has been signed off as resolved.",
            ),
        ),
        migrations.AddField(
            model_name="benchmarkrun",
            name="resolution_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff notes detailing root cause remediation (e.g. bugfix, environment repair).",
            ),
        ),
        migrations.AddField(
            model_name="benchmarkrun",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when this run defect was signed off as resolved.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="benchmarkrun",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff user who reviewed and signed off on this run's defect resolution.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_benchmark_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="benchmarkresult",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="benchmarking.benchmarkrun",
            ),
        ),
    ]
