import os
import tempfile
from django.core.management.base import BaseCommand
from django.core.files import File
from background_resources.models import Document
from background_resources.rag_service import RAGService
from django.apps import apps
from django.conf import settings

class Command(BaseCommand):
    help = 'Syncs the current project architectural documentation and Agent Skills to the knowledge base (RAG).'

    def handle(self, *args, **options):
        self.stdout.write("Generating Architectural Documentation...")

        doc_lines = [
            "# Verbal Architectural Knowledge Sync",
            "This document is automatically generated by the NightManager to ensure models have up-to-date context.",
            "",
        ]

        # 1. Introspect Metacognition Models
        doc_lines.append("## Metacognition Models")
        for model in apps.get_app_config('metacognition').get_models():
            doc_lines.append(f"### Model: {model.__name__}")
            for field in model._meta.get_fields():
                if hasattr(field, 'get_internal_type'):
                    doc_lines.append(f"- **{field.name}** ({field.get_internal_type()}): {getattr(field, 'help_text', '')}")
            doc_lines.append("")

        # 2. Ingest Agent Skills
        skills_dir = os.path.join(settings.BASE_DIR, '.agents', 'skills')
        if os.path.exists(skills_dir):
            doc_lines.append("## Available Agent Skills")
            for skill_name in os.listdir(skills_dir):
                skill_path = os.path.join(skills_dir, skill_name, 'SKILL.md')
                if os.path.exists(skill_path):
                    with open(skill_path, 'r') as f:
                        doc_lines.append(f"### Skill: {skill_name}")
                        doc_lines.append("```markdown")
                        doc_lines.append(f.read())
                        doc_lines.append("```")
                        doc_lines.append("")

        full_markdown = "\n".join(doc_lines)

        # Write to a temp file and ingest it
        fd, temp_path = tempfile.mkstemp(suffix=".md")
        try:
            with os.fdopen(fd, 'w') as f:
                f.write(full_markdown)

            with open(temp_path, 'rb') as f:
                title = "Verbal Architectural Core (Auto-Synced)"
                django_doc = Document.objects.filter(title=title).first()
                if not django_doc:
                    django_doc = Document(title=title, author="NightManager")
                
                if django_doc.file:
                    django_doc.file.delete(save=False)
                
                django_doc.file.save("architecture_sync.md", File(f), save=True)

            self.stdout.write(self.style.SUCCESS(f"Saved document '{django_doc.title}' to DB. Triggering RAG Ingestion..."))
            
            # Now ingest the document into vectorstore
            rag = RAGService()
            rag.ingest_queryset_documents(Document.objects.filter(id=django_doc.id))

            self.stdout.write(self.style.SUCCESS("Successfully synced architecture to RAG vectorstore!"))
            
        finally:
            if os.path.exists(temp_path):
                os.remove(temp_path)
