# Generated by Django 5.2.7 on 2026-05-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("background_resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "authors",
                    models.TextField(
                        blank=True, help_text="Comma separated list of parsed authors"
                    ),
                ),
                ("abstract", models.TextField(blank=True)),
                (
                    "journal",
                    models.CharField(
                        blank=True,
                        help_text="Journal, conference, or publication name",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "publication_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("volume", models.CharField(blank=True, max_length=50, null=True)),
                ("issue", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.CharField(blank=True, max_length=50, null=True)),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("parsed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grobid_metadata",
                        to="background_resources.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_reference_string",
                    models.TextField(help_text="The raw bibliography string."),
                ),
                (
                    "context_text",
                    models.TextField(
                        blank=True,
                        help_text="The sentence(s) in the source document where this citation occurs.",
                        null=True,
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        help_text="The document that contains the bibliography.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_citations",
                        to="grobid_client.reference",
                    ),
                ),
                (
                    "target_reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cited reference.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_citations",
                        to="grobid_client.reference",
                    ),
                ),
            ],
        ),
    ]
