# Generated by Django 5.2.7 on 2026-05-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grobid_client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="tei_xml",
            field=models.TextField(
                blank=True, help_text="Cached output from Grobid", null=True
            ),
        ),
    ]
