# Generated by Django 5.2.7 on 2026-05-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grobid_client", "0002_reference_tei_xml"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationGraphExplorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Citation Graph Explorer",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="reference",
            name="extended_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extended structured metadata from TEI XML",
                null=True,
            ),
        ),
    ]
