# Generated by Django 6.0.5 on 2026-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grobid_client", "0003_citationgraphexplorer_reference_extended_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="year",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
