# Generated by Django 6.0.5 on 2026-05-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grobid_client", "0004_alter_reference_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="journal",
            field=models.CharField(
                blank=True,
                help_text="Journal, conference, or publication name",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
